### ISSUE TITLE
How do you extend prototypes as suggested in globalBootStrap()?

### ISSUE THREAD

**Issue by staff0rd** [MarkoSulamagi/screeps#9]
[This](https://github.com/MarkoSulamagi/Screeps-typescript-skeleton/issues/new) suggests that interfaces can't be extended.

**Comment by MarkoSulamagi** [comment]
I can comment on this tomorrow.

**Comment by MarkoSulamagi** [comment]
Although, Typescript classes and inheritance are compiled to JavaScript prototypes, you can't easily extend Screeps' object prototypes, because interface doesn't allow it. 

1) One possibility is to clone the "screeps-typescript-declarations" module and add your own method description to the interfaces. Then you can extend the functionality the same way as you would using vanilla Javascript.

```
// Declaration
interface creep {
  prototype: Creep;

  ..
  foo(): void;
}

// Implementation
Creep.prototype.foo = function() { console.log("bar"); } `
```

Drawback for this is that if "screeps-typescript-declarations" project is updated then you would have to merge the changes manually to your project. Which is quite inconvenient. 

2) For my own project, I don't extend Screeps object prototypes at all and instead, wrap them in seperate classes. 

For example:

```
interface SuperCreepInterface {
  creep: Creep;
  setCreep(creep: Creep): void;
  foo(): void;
}

class SuperCreep implements SuperCreepInterface {
  creep: Creep = null;

  public function setCreep(creep: Creep) {
    this.creep = creep;
  }

  public function foo() {
    console.log(this.creep);
  }
}
```

Sad part for this solution is that it's not very pro JavaScript. JS is popular by its prototypes and unfortunately we're going more "Java" like. It's not supposed to be like that. 

3) If you have a better solution then I'm all ears. I'd like to know how to solve it also. 

I linked this issue to GitHub page and also asked opinion from some people in IRC.
Thanks for bringing it up.

**Comment by NhanHo** [comment]
```
//prototype.d.ts
interface Creep {
    foo():void;
}
```

```
//prototype.ts
Creep.prototype.foo = function(){};
```

```
//foo.ts
let c: Creep = Game.creeps["foo"];
c.foo(); //This will compile without error

//Just for good measure, we can see that this will also compile without error
c.attack(Game.creeps["bar"]); 
```

It seems like TS compiler knows to merge different ambient module, so all we have to do is declaring an interface Creep in a .d.ts file, containing all the new function that we're extending the prototype with

**Comment by MarkoSulamagi** [comment]
This seems to work well, NhanHo. Thanks.

I'll close this issue. Feel free to reopen it if there's something to add.
